create table if not exists public.character_views (
  id bigint generated by default as identity primary key,
  character_id text not null unique,
  character_name text not null,
  views bigint not null default 1,
  updated_at timestamptz not null default now()
);

create index if not exists character_views_views_idx
  on public.character_views (views desc);

-- The application uses the service-role key ONLY on the server.
-- No browser code talks directly to this table.
