create table if not exists public.character_views (
  id bigint generated by default as identity primary key,
  character_id text not null unique,
  character_name text not null,
  views bigint not null default 1,
  updated_at timestamptz not null default now()
);

create index if not exists character_views_views_idx
  on public.character_views (views desc);

alter table public.character_views enable row level security;

create or replace function public.increment_character_view(
  p_character_id text,
  p_character_name text
)
returns void
language sql
security invoker
as $$
  insert into public.character_views as cv (
    character_id,
    character_name,
    views,
    updated_at
  )
  values (
    p_character_id,
    p_character_name,
    1,
    now()
  )
  on conflict (character_id)
  do update set
    character_name = excluded.character_name,
    views = cv.views + 1,
    updated_at = now();
$$;

revoke execute
on function public.increment_character_view(text, text)
from public, anon, authenticated;

grant execute
on function public.increment_character_view(text, text)
to service_role;
